defult:
  width: &width 530
  height: &height 300

plot_1:
  height: *height
  width: *width
  title: 累计净值
  yaxis_label: 累计径直
  legend:
    - 策略累计净值
    - 基准累计净值

plot_2:
  height: *height
  width: *width
  title: 累计净值（波动率调整）
  yaxis_label: 累计净值
  legend:
    - 策略累计净值（调整后）
    - 基准累计净值

plot_3:
  height: *height
  width: *width
  title: 对数轴累计净值曲线
  yaxis_label: 累计净值
  legend:
    - 策略累计净值
    - 基准累计净值

plot_4:
  height: *height
  width: *width
  title: 日收益率
  yaxis_label: 日收益率
  legend:
    - 日收益率

plot_5:
  height: *height
  width: *width
  title: 累计beta
  yaxis_label: 累计beta
  legend:
    - 6个月
    - 12个月

plot_6:
  height: *height
  width: *width
  title: 累计夏普率
  yaxis_label: 夏普率
  legend:
    - 累计夏普率
    - 平均夏普率

plot_8:
  height: *height
  width: *width
  title: 前五大回撤
  yaxis_label: 累计收益
  legend:
    - 策略累计收益率

plot_9:
  width: *width
  height: *height
  title: 月收益率

plot_10:
  height: *height
  width: *width
  title: 年度收益率
  xaxis_label: 收益率
  yaxis_label: 年
  legend: 均值
  annotation : 年度收益率

plot_11:
  height: *height
  width: *width
  title: 月度收益率分布
  yaxis_label:
  xaxis_label: 收益率
  legend: 均值
  annotation : 月数

plot_17:
  height: *height
  width: *width
  title: 持仓占比
  yaxis_label: 总仓位
  legend:
    - 多头持仓
    - 空头持仓
    - 净持仓

plot_18:
  height: *height
  width: *width
  title: 前十大重仓股持仓占比
  yaxis_label: 单只证券持仓

plot_20:
  height: *height
  width: *width
  title: 每日持有股票数
  yaxis_label: 持有股票数
  legend:
    - 每日持有股票数
    - 按月平均日持有股票数
    - 平均日持有股票数

plot_21:
  height: *height
  width: *width
  title: 每日换手率
  yaxis_label: 换手率
  legend:
    - 每日换手率
    - 按月平均换手率
    - 平均换手率

plot_24:
  height: *height
  width: *width
  yaxis_label: 可信度
  xaxis_label: 每次交易的胜率分布
  title: 回转交易盈利概率分布
  legend:
    - 胜率
    - 可信度

plot_25:
  height: *height
  width: *width
  title: 回转交易持续时间分布（日）
  yaxis_label: 回转交易数量
  xaxis_label: 天数
  legend: 均值
  annotation : 回转交易数量
  legend: 回转交易持续时间均值

plot_26:
  height: *height
  width: *width
  title: 回转交易盈亏分布
  annotation : 回转交易数量
  title: 回转交易盈亏分布
  yaxis_label: 回转交易数量
  xaxis_label: 盈亏（元）
  legend: 回转交易盈亏均值

plot_27:
  height: *height
  width: *width
  title: 回转交易收益率分布
  yaxis_label: 回转交易数量
  xaxis_label: 收益率
  legend: 均值
  annotation : 回转交易数量

scenario_1:
  height: *height
  width: *width
  title: 特殊时期净值 - 创业板牛市（2015-03-03 - 2015-06-03）
  yaxis_label: 累计净值
  legend:
    - 策略累计净值
    - 基准累计净值

scenario_2:
  height: *height
  width: *width
  title: 特殊时期净值 - 牛市调整期（2014-12-01 - 2015-03-01）
  yaxis_label: 累计收益
  legend:
    - 策略累计净值
    - 基准累计净值

scenario_3:
  height: *height
  width: *width
  title: 特殊时期净值 - 股灾暴跌（2015-06-01 - 2015-09-01）
  yaxis_label: 累计净值
  legend:
    - 策略累计净值
    - 基准累计净值

scenario_4:
  height: *height
  width: *width
  title: 特殊时期净值 - 熔断暴跌（2015-12-15 - 2016-03-15）
  yaxis_label: 累计净值
  legend:
    - 策略累计净值
    - 基准累计净值

scenario_5:
  height: *height
  width: *width
  title: 特殊时期净值 - 股灾后平稳期（2016-05-05 - 2016-08-05）
  yaxis_label: 累计净值
  legend:
    - 策略累计净值
    - 基准累计净值